###############################################################################
#                          Generated on liqiankun                             #
###############################################################################
version: "3.1"
services:

    # mysql:
    #   image: mysql:5.7
    #   container_name: lnmp-mysql
    #   working_dir: /usr/local/mysql/5.7
    #   volumes:
    #     - ./mysql/conf :/etc/mysql/conf.d
    #     - ./mysql/data :/var/lib/mysql
    #   environment:
    #     - MYSQL_ROOT_PASSWORD=123456
    #     - MYSQL_DATABASE=liqiankun
    #     - MYSQL_USER=root
    #     - MYSQL_PASSWORD=root
    #   ports:
    #     - "3308:3306"
    #   networks:
    #     - mynet

    nginx:
      image: liqiankun/nginx:1.20.1-alpine3.13
      container_name: lnmp-nginx
      working_dir: /application
      volumes:
        - ../www:/application
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/conf.d:/etc/nginx/conf.d       
      ports:
        - "80:80"
        - "8082:8082"
        - "8083:8083"
        - "8084:8084"
        - "443:443"
      labels:
        - "com.centurylinklabs.watchtower.enable=true"  
      networks:
        - mynet

    php-fpm:
      image: liqiankun/php:8.0.7-fpm-alpine3.13
      container_name: lnmp-php-fpm
      volumes:
        - ../www:/application
        - ./php/8.0/over-php.ini:/usr/local/etc/php/conf.d/over-php.ini
      labels: 
        - "com.centurylinklabs.watchtower.enable=true"
      # ports:
      #   - "9000:9000"
      networks:
        - mynet
    
    redis:
      image: liqiankun/redis:6.2.4-alpine3.13
      container_name: lnmp-redis
      working_dir: /usr/local/redis/6.2.4
      labels:
        - "com.centurylinklabs.watchtower.enable=true"
      ports:
        - "6379:6379"
      networks:
        - mynet
    
    mysql:
      image: liqiankun/mysql:8.0.25
      container_name: lnmp-mysql8
      working_dir: /usr/local/mysql/8.0.25
      command:
        - --default-authentication-plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      volumes:
        - ../data/mysql/8/data :/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=liqiankun
        - MYSQL_USER=root2
        - MYSQL_PASSWORD=root2
      ports:
        - "3306:3306"
      labels:
        - "com.centurylinklabs.watchtower.enable=true"
      networks:
        - mynet

    node-server:
      image: liqiankun/node:14.17.0-alpine3.13
      container_name: lnmp-node
      entrypoint: sh
      labels:
        - "com.centurylinklabs.watchtower.enable=true"
      command:
        - -c
        - |
          tail -f /dev/null
      networks:
        - mynet

    golang:
      image: liqiankun/golang:1.16-alpine3.13
      container_name: lnmp-golang
      labels:
        - "com.centurylinklabs.watchtower.enable=true"
      entrypoint: sh  
      command:
        - -c
        - |
          tail -f /dev/null  
      networks:
        - mynet

    watchtower:
      image: containrrr/watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      command: --interval 30  --label-enable
      labels:
      - "com.centurylinklabs.watchtower.enable=true"
      networks:
        - mynet
  
networks:
  mynet:
    driver: bridge
